[versions]
kotlin = "2.1.20"
minecraft = "1.20.1"

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment = "2023.09.03"

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge = "47.4.0"
modDevGradle = "2.0.107"
kotlinForForge = "4.11.0"
kotest = "6.0.4"
mockk = "1.14.6"

kotlinxSerializationJson = "1.9.0"
benManesVersion = "0.52.0"
modPublisher = "2.1.6"

[libraries]
kotlinforforge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlinForForge" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Testing
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[bundles]
testing = ["kotest-framework-engine", "kotest-runner-junit5", "kotest-assertions-core", "kotest-property", "mockk"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm" }
modDevGradle = { id = "net.neoforged.moddev.legacyforge", version.ref = "modDevGradle" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
benManesVersions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersion" }
kotest = { id = "io.kotest", version.ref = "kotest" }
modPublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modPublisher" }